// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("f390b28c-215a-44b7-b772-0a7658287443"),
	Debug("f501ea5a-8bec-45ee-8fdf-9482cb463189"),
	Info("2fb1cf0e-5ec7-452d-9748-e2af51103a92"),
	Warning("e1eb7d9e-0f6c-4943-9648-b2031f5df3f8"),
	Error("38b9b1dc-802c-42a9-b0d5-a33df24f790b"),
	Critical("c373b579-3ff4-43cf-9b90-3c39d7f714d9");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
