// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("36edb261-759f-4b46-b55a-cada6b8346ee"),
	FORMATTING("ae0223bd-d24a-473d-834c-00e9090439fb"),
	IMAGES("a5c49b42-82c3-4a4a-ac51-e69bc079436b"),
	LINKS("f6b4f592-fc82-4167-86c4-e3130bb0ed64"),
	STYLES("25f80093-3f4f-4a87-9508-175153cc3023"),
	TABLES("6bdfea47-0c0b-4d02-875f-d0c9dc964bff");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
