// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("1cb76c46-41e2-48d1-97d3-1b322835dfec"),
	ISO_8859_1("e11546c6-2889-4b3f-a938-cc979d2bac22"),
	UTF_8("3832567c-d996-432c-914f-4c9b355f40c2"),
	UTF_16BE("233d9165-e576-48db-8796-b24169b5a14e"),
	UTF_16LE("36e06b25-9f42-4839-883c-6b64764e7c35"),
	UTF_16("0f1ea1c3-03db-4c68-861b-45031b312ee8");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
