// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testvirtualsrollcontainer.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestVirtualSrollContainer module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestData_GenerateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestVirtualSrollContainer.ACT_TestData_Generate");
		return builder;
	}

	public static void aCT_TestData_Generate(IContext context)
	{
		aCT_TestData_GenerateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ViewTestData_SaveBuilder(
		testvirtualsrollcontainer.proxies.TestData _testData,
		testvirtualsrollcontainer.proxies.ViewTestData _viewTestData
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestVirtualSrollContainer.ACT_ViewTestData_Save");
		builder = builder.withParam("TestData", _testData);
		builder = builder.withParam("ViewTestData", _viewTestData);
		return builder;
	}

	public static void aCT_ViewTestData_Save(
		IContext context,
		testvirtualsrollcontainer.proxies.TestData _testData,
		testvirtualsrollcontainer.proxies.ViewTestData _viewTestData
	)
	{
		aCT_ViewTestData_SaveBuilder(
				_testData,
				_viewTestData
			)
			.execute(context);
	}
}
