// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testvirtualsrollcontainer.proxies;

public class TestData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestVirtualSrollContainer.TestData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SeqNbr("SeqNbr"),
		Name("Name"),
		TestData_Language("TestVirtualSrollContainer.TestData_Language"),
		TestData_TimeZone("TestVirtualSrollContainer.TestData_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testDataMendixObject)
	{
		if (testDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!testDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testDataMendixObject = testDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testvirtualsrollcontainer.proxies.TestData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testvirtualsrollcontainer.proxies.TestData(context, mendixObject);
	}

	public static testvirtualsrollcontainer.proxies.TestData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testvirtualsrollcontainer.proxies.TestData.initialize(context, mendixObject);
	}

	public static java.util.List<testvirtualsrollcontainer.proxies.TestData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testvirtualsrollcontainer.proxies.TestData.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr()
	{
		return getSeqNbr(getContext());
	}

	/**
	 * @param context
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SeqNbr.toString());
	}

	/**
	 * Set value of SeqNbr
	 * @param seqnbr
	 */
	public final void setSeqNbr(java.lang.Integer seqnbr)
	{
		setSeqNbr(getContext(), seqnbr);
	}

	/**
	 * Set value of SeqNbr
	 * @param context
	 * @param seqnbr
	 */
	public final void setSeqNbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seqnbr)
	{
		getMendixObject().setValue(context, MemberNames.SeqNbr.toString(), seqnbr);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestData_Language
	 */
	public final system.proxies.Language getTestData_Language() throws com.mendix.core.CoreException
	{
		return getTestData_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of TestData_Language
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Language getTestData_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestData_Language.toString());
		if (identifier != null) {
			result = system.proxies.Language.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestData_Language
	 * @param testdata_language
	 */
	public final void setTestData_Language(system.proxies.Language testdata_language)
	{
		setTestData_Language(getContext(), testdata_language);
	}

	/**
	 * Set value of TestData_Language
	 * @param context
	 * @param testdata_language
	 */
	public final void setTestData_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language testdata_language)
	{
		if (testdata_language == null) {
			getMendixObject().setValue(context, MemberNames.TestData_Language.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestData_Language.toString(), testdata_language.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestData_TimeZone
	 */
	public final system.proxies.TimeZone getTestData_TimeZone() throws com.mendix.core.CoreException
	{
		return getTestData_TimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of TestData_TimeZone
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.TimeZone getTestData_TimeZone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.TimeZone result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestData_TimeZone.toString());
		if (identifier != null) {
			result = system.proxies.TimeZone.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestData_TimeZone
	 * @param testdata_timezone
	 */
	public final void setTestData_TimeZone(system.proxies.TimeZone testdata_timezone)
	{
		setTestData_TimeZone(getContext(), testdata_timezone);
	}

	/**
	 * Set value of TestData_TimeZone
	 * @param context
	 * @param testdata_timezone
	 */
	public final void setTestData_TimeZone(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.TimeZone testdata_timezone)
	{
		if (testdata_timezone == null) {
			getMendixObject().setValue(context, MemberNames.TestData_TimeZone.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestData_TimeZone.toString(), testdata_timezone.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testvirtualsrollcontainer.proxies.TestData that = (testvirtualsrollcontainer.proxies.TestData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
