// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testvirtualsrollcontainer.proxies;

public class ViewTestData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject viewTestDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestVirtualSrollContainer.ViewTestData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SeqNbr("SeqNbr"),
		Name("Name"),
		LanguageCode("LanguageCode"),
		LanguageDescription("LanguageDescription"),
		TimeZoneCode("TimeZoneCode"),
		TimeZoneDescription("TimeZoneDescription"),
		TimeZoneRawOffset("TimeZoneRawOffset"),
		ViewTestData_TestData("TestVirtualSrollContainer.ViewTestData_TestData"),
		ViewTestData_Language("TestVirtualSrollContainer.ViewTestData_Language"),
		ViewTestData_TimeZone("TestVirtualSrollContainer.ViewTestData_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ViewTestData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ViewTestData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject viewTestDataMendixObject)
	{
		if (viewTestDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!viewTestDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.viewTestDataMendixObject = viewTestDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testvirtualsrollcontainer.proxies.ViewTestData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testvirtualsrollcontainer.proxies.ViewTestData(context, mendixObject);
	}

	public static testvirtualsrollcontainer.proxies.ViewTestData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testvirtualsrollcontainer.proxies.ViewTestData.initialize(context, mendixObject);
	}

	public static java.util.List<testvirtualsrollcontainer.proxies.ViewTestData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testvirtualsrollcontainer.proxies.ViewTestData.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr()
	{
		return getSeqNbr(getContext());
	}

	/**
	 * @param context
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SeqNbr.toString());
	}

	/**
	 * Set value of SeqNbr
	 * @param seqnbr
	 */
	public final void setSeqNbr(java.lang.Integer seqnbr)
	{
		setSeqNbr(getContext(), seqnbr);
	}

	/**
	 * Set value of SeqNbr
	 * @param context
	 * @param seqnbr
	 */
	public final void setSeqNbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seqnbr)
	{
		getMendixObject().setValue(context, MemberNames.SeqNbr.toString(), seqnbr);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of LanguageCode
	 */
	public final java.lang.String getLanguageCode()
	{
		return getLanguageCode(getContext());
	}

	/**
	 * @param context
	 * @return value of LanguageCode
	 */
	public final java.lang.String getLanguageCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LanguageCode.toString());
	}

	/**
	 * Set value of LanguageCode
	 * @param languagecode
	 */
	public final void setLanguageCode(java.lang.String languagecode)
	{
		setLanguageCode(getContext(), languagecode);
	}

	/**
	 * Set value of LanguageCode
	 * @param context
	 * @param languagecode
	 */
	public final void setLanguageCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String languagecode)
	{
		getMendixObject().setValue(context, MemberNames.LanguageCode.toString(), languagecode);
	}

	/**
	 * @return value of LanguageDescription
	 */
	public final java.lang.String getLanguageDescription()
	{
		return getLanguageDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of LanguageDescription
	 */
	public final java.lang.String getLanguageDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LanguageDescription.toString());
	}

	/**
	 * Set value of LanguageDescription
	 * @param languagedescription
	 */
	public final void setLanguageDescription(java.lang.String languagedescription)
	{
		setLanguageDescription(getContext(), languagedescription);
	}

	/**
	 * Set value of LanguageDescription
	 * @param context
	 * @param languagedescription
	 */
	public final void setLanguageDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String languagedescription)
	{
		getMendixObject().setValue(context, MemberNames.LanguageDescription.toString(), languagedescription);
	}

	/**
	 * @return value of TimeZoneCode
	 */
	public final java.lang.String getTimeZoneCode()
	{
		return getTimeZoneCode(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZoneCode
	 */
	public final java.lang.String getTimeZoneCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZoneCode.toString());
	}

	/**
	 * Set value of TimeZoneCode
	 * @param timezonecode
	 */
	public final void setTimeZoneCode(java.lang.String timezonecode)
	{
		setTimeZoneCode(getContext(), timezonecode);
	}

	/**
	 * Set value of TimeZoneCode
	 * @param context
	 * @param timezonecode
	 */
	public final void setTimeZoneCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezonecode)
	{
		getMendixObject().setValue(context, MemberNames.TimeZoneCode.toString(), timezonecode);
	}

	/**
	 * @return value of TimeZoneDescription
	 */
	public final java.lang.String getTimeZoneDescription()
	{
		return getTimeZoneDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZoneDescription
	 */
	public final java.lang.String getTimeZoneDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZoneDescription.toString());
	}

	/**
	 * Set value of TimeZoneDescription
	 * @param timezonedescription
	 */
	public final void setTimeZoneDescription(java.lang.String timezonedescription)
	{
		setTimeZoneDescription(getContext(), timezonedescription);
	}

	/**
	 * Set value of TimeZoneDescription
	 * @param context
	 * @param timezonedescription
	 */
	public final void setTimeZoneDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezonedescription)
	{
		getMendixObject().setValue(context, MemberNames.TimeZoneDescription.toString(), timezonedescription);
	}

	/**
	 * @return value of TimeZoneRawOffset
	 */
	public final java.lang.Integer getTimeZoneRawOffset()
	{
		return getTimeZoneRawOffset(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZoneRawOffset
	 */
	public final java.lang.Integer getTimeZoneRawOffset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TimeZoneRawOffset.toString());
	}

	/**
	 * Set value of TimeZoneRawOffset
	 * @param timezonerawoffset
	 */
	public final void setTimeZoneRawOffset(java.lang.Integer timezonerawoffset)
	{
		setTimeZoneRawOffset(getContext(), timezonerawoffset);
	}

	/**
	 * Set value of TimeZoneRawOffset
	 * @param context
	 * @param timezonerawoffset
	 */
	public final void setTimeZoneRawOffset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer timezonerawoffset)
	{
		getMendixObject().setValue(context, MemberNames.TimeZoneRawOffset.toString(), timezonerawoffset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ViewTestData_TestData
	 */
	public final testvirtualsrollcontainer.proxies.TestData getViewTestData_TestData() throws com.mendix.core.CoreException
	{
		return getViewTestData_TestData(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewTestData_TestData
	 * @throws com.mendix.core.CoreException
	 */
	public final testvirtualsrollcontainer.proxies.TestData getViewTestData_TestData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testvirtualsrollcontainer.proxies.TestData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ViewTestData_TestData.toString());
		if (identifier != null) {
			result = testvirtualsrollcontainer.proxies.TestData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ViewTestData_TestData
	 * @param viewtestdata_testdata
	 */
	public final void setViewTestData_TestData(testvirtualsrollcontainer.proxies.TestData viewtestdata_testdata)
	{
		setViewTestData_TestData(getContext(), viewtestdata_testdata);
	}

	/**
	 * Set value of ViewTestData_TestData
	 * @param context
	 * @param viewtestdata_testdata
	 */
	public final void setViewTestData_TestData(com.mendix.systemwideinterfaces.core.IContext context, testvirtualsrollcontainer.proxies.TestData viewtestdata_testdata)
	{
		if (viewtestdata_testdata == null) {
			getMendixObject().setValue(context, MemberNames.ViewTestData_TestData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ViewTestData_TestData.toString(), viewtestdata_testdata.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ViewTestData_Language
	 */
	public final system.proxies.Language getViewTestData_Language() throws com.mendix.core.CoreException
	{
		return getViewTestData_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewTestData_Language
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Language getViewTestData_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ViewTestData_Language.toString());
		if (identifier != null) {
			result = system.proxies.Language.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ViewTestData_Language
	 * @param viewtestdata_language
	 */
	public final void setViewTestData_Language(system.proxies.Language viewtestdata_language)
	{
		setViewTestData_Language(getContext(), viewtestdata_language);
	}

	/**
	 * Set value of ViewTestData_Language
	 * @param context
	 * @param viewtestdata_language
	 */
	public final void setViewTestData_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language viewtestdata_language)
	{
		if (viewtestdata_language == null) {
			getMendixObject().setValue(context, MemberNames.ViewTestData_Language.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ViewTestData_Language.toString(), viewtestdata_language.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ViewTestData_TimeZone
	 */
	public final system.proxies.TimeZone getViewTestData_TimeZone() throws com.mendix.core.CoreException
	{
		return getViewTestData_TimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewTestData_TimeZone
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.TimeZone getViewTestData_TimeZone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.TimeZone result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ViewTestData_TimeZone.toString());
		if (identifier != null) {
			result = system.proxies.TimeZone.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ViewTestData_TimeZone
	 * @param viewtestdata_timezone
	 */
	public final void setViewTestData_TimeZone(system.proxies.TimeZone viewtestdata_timezone)
	{
		setViewTestData_TimeZone(getContext(), viewtestdata_timezone);
	}

	/**
	 * Set value of ViewTestData_TimeZone
	 * @param context
	 * @param viewtestdata_timezone
	 */
	public final void setViewTestData_TimeZone(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.TimeZone viewtestdata_timezone)
	{
		if (viewtestdata_timezone == null) {
			getMendixObject().setValue(context, MemberNames.ViewTestData_TimeZone.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ViewTestData_TimeZone.toString(), viewtestdata_timezone.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return viewTestDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testvirtualsrollcontainer.proxies.ViewTestData that = (testvirtualsrollcontainer.proxies.ViewTestData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
