// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testvirtualsrollcontainer.proxies;

public enum WidgetAction
{
	Reload("2331b893-667a-4cb1-a287-f89d655c5c7a"),
	Refresh("82680888-e8f8-4739-bc30-d9b0a729da69");

	private final java.lang.String i18nCaptionKey;
	
	private WidgetAction(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
