// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testvirtualsrollcontainer.proxies;

public class WidgetContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject widgetContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestVirtualSrollContainer.WidgetContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataChangeTrigger("DataChangeTrigger"),
		WidgetAction("WidgetAction"),
		WidgetContext_Session("TestVirtualSrollContainer.WidgetContext_Session");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WidgetContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WidgetContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject widgetContextMendixObject)
	{
		if (widgetContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!widgetContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.widgetContextMendixObject = widgetContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testvirtualsrollcontainer.proxies.WidgetContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testvirtualsrollcontainer.proxies.WidgetContext(context, mendixObject);
	}

	public static testvirtualsrollcontainer.proxies.WidgetContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testvirtualsrollcontainer.proxies.WidgetContext.initialize(context, mendixObject);
	}

	public static java.util.List<testvirtualsrollcontainer.proxies.WidgetContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testvirtualsrollcontainer.proxies.WidgetContext.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DataChangeTrigger
	 */
	public final java.util.Date getDataChangeTrigger()
	{
		return getDataChangeTrigger(getContext());
	}

	/**
	 * @param context
	 * @return value of DataChangeTrigger
	 */
	public final java.util.Date getDataChangeTrigger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DataChangeTrigger.toString());
	}

	/**
	 * Set value of DataChangeTrigger
	 * @param datachangetrigger
	 */
	public final void setDataChangeTrigger(java.util.Date datachangetrigger)
	{
		setDataChangeTrigger(getContext(), datachangetrigger);
	}

	/**
	 * Set value of DataChangeTrigger
	 * @param context
	 * @param datachangetrigger
	 */
	public final void setDataChangeTrigger(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datachangetrigger)
	{
		getMendixObject().setValue(context, MemberNames.DataChangeTrigger.toString(), datachangetrigger);
	}

	/**
	 * Get value of WidgetAction
	 * @param widgetaction
	 */
	public final testvirtualsrollcontainer.proxies.WidgetAction getWidgetAction()
	{
		return getWidgetAction(getContext());
	}

	/**
	 * @param context
	 * @return value of WidgetAction
	 */
	public final testvirtualsrollcontainer.proxies.WidgetAction getWidgetAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.WidgetAction.toString());
		if (obj == null) {
			return null;
		}
		return testvirtualsrollcontainer.proxies.WidgetAction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of WidgetAction
	 * @param widgetaction
	 */
	public final void setWidgetAction(testvirtualsrollcontainer.proxies.WidgetAction widgetaction)
	{
		setWidgetAction(getContext(), widgetaction);
	}

	/**
	 * Set value of WidgetAction
	 * @param context
	 * @param widgetaction
	 */
	public final void setWidgetAction(com.mendix.systemwideinterfaces.core.IContext context, testvirtualsrollcontainer.proxies.WidgetAction widgetaction)
	{
		if (widgetaction != null) {
			getMendixObject().setValue(context, MemberNames.WidgetAction.toString(), widgetaction.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.WidgetAction.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WidgetContext_Session
	 */
	public final system.proxies.Session getWidgetContext_Session() throws com.mendix.core.CoreException
	{
		return getWidgetContext_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of WidgetContext_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getWidgetContext_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WidgetContext_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WidgetContext_Session
	 * @param widgetcontext_session
	 */
	public final void setWidgetContext_Session(system.proxies.Session widgetcontext_session)
	{
		setWidgetContext_Session(getContext(), widgetcontext_session);
	}

	/**
	 * Set value of WidgetContext_Session
	 * @param context
	 * @param widgetcontext_session
	 */
	public final void setWidgetContext_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session widgetcontext_session)
	{
		if (widgetcontext_session == null) {
			getMendixObject().setValue(context, MemberNames.WidgetContext_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WidgetContext_Session.toString(), widgetcontext_session.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return widgetContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testvirtualsrollcontainer.proxies.WidgetContext that = (testvirtualsrollcontainer.proxies.WidgetContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
