// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("50a3d664-7961-4748-b0d2-208f4365d724"),
	startsWith("70dd2959-baf9-47f1-9f1e-8ca35bc7affb"),
	endsWith("99819e97-d702-44d3-8dda-0bc8dc36c15f"),
	between("3e0e398f-bb5b-4731-a033-604ff65db2fd"),
	greater("c90ad9d2-154c-47f5-85ce-16283695cc70"),
	greaterEqual("5ce25bac-5029-404d-a76c-9343801f3c69"),
	equal("2dce868b-259e-485e-891c-e0f3a7412d01"),
	notEqual("521118e1-caaf-4ab2-bda2-544bd6fb8be1"),
	smaller("bc9249b1-32ed-4f62-b61f-41293a74b423"),
	smallerEqual("0d30b056-bced-40da-927d-a1bce3b8a5eb"),
	empty("69358937-cbca-48b8-8d57-7eb9f7674982"),
	notEmpty("8981843f-f530-4c94-808f-82fe7374a758");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
